MODIFY_INVENTORIES gamerule
NucleoidMC/plasmid pull request #133
Opened 2021-04-06 14:23 UTC by Geek202

Adds a new gamerule for minigames that specifies whether players can move items around in their inventories. The villager 'no' sound is also played if users can't move items, however there are some cases where it doesn't (mostly when shift-clicking items)

2021-04-06 14:38 UTC, Gegy approved these changes
Looks good to me. Thank you! :)

2021-04-06 16:21 UTC, Geek202 commented
Just looked at this again and thought that there should probably be a seperate rule for armour slots, as games may only want to lock the armour but be able to move stuff in their inventory

2021-04-06 17:39 UTC, haykam821 commented
The `MODIFY_ARMOUR` rule and related names should be changed to `MODIFY_ARMOR`.

2021-04-06 17:40 UTC, haykam821 requested changes
The `MODIFY_ARMOUR` rule should be renamed to `MODIFY_ARMOR` to match the Yarn and American English spelling.

2021-04-06 19:56 UTC, Geek202 commented
Done!

2021-04-07 07:06 UTC, Gegy commented
It might make sense for MODIFY_INVENTORY to include MODIFY_ARMOR's behavior, given it might be confusing to disable inventory mutation but armor still works. I'm not sure if there's ever a use case for being able to modify armor but not the inventory- if there is, maybe that could work by inventory disallowed and armor explicitly allowed?

2021-04-07 09:31 UTC, Gegy approved these changes

2021-04-08 09:03 UTC, merged