Add new Mangrove type values to WoodType enum
NucleoidMC/plasmid pull request #250
Opened 2022-10-10 03:53 UTC by michizhou

Added values for Mangrove type to the WoodType enum. Fixes #235.

2022-11-16 15:43 UTC, haykam821 approved these changes

2022-11-16 15:44 UTC, haykam821 requested changes

2022-11-16 15:44 UTC, haykam821 commented on src/main/java/xyz/nucleoid/plasmid/util/WoodType.java
>      DARK_OAK(Blocks.DARK_OAK_SAPLING, Blocks.DARK_OAK_LEAVES, Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.DARK_OAK_STAIRS, Blocks.DARK_OAK_FENCE, Blocks.DARK_OAK_FENCE_G
```suggestion
    DARK_OAK(Blocks.DARK_OAK_SAPLING, Blocks.DARK_OAK_LEAVES, Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Blocks.DARK_OAK_STAIRS, Blocks.DARK_OAK_FENCE, Blocks.DARK_OAK_FENCE_GATE, Blocks.DARK_OAK_DOOR, Blocks.DARK_OAK_SIGN, Blocks.DARK_OAK_BUTTON, Blocks.DARK_OAK_PRESSURE_PLATE, Items.DARK_OAK_BOAT),
```

2022-11-16 17:46 UTC, haykam821 approved these changes

2022-12-03 18:54 UTC, Patbox approved these changes

2022-12-03 18:54 UTC, merged