Make Scoreboards Translatable (Updated)
NucleoidMC/plasmid pull request #59
Opened 2020-11-21 17:52 UTC by arthurbambou

2020-11-21 18:08 UTC, LambdAurora approved these changes

2020-11-23 11:13 UTC, Gegy requested changes
I think unfortunately by the nature of `Text` and scoreboards, exposing access to send Text over the scoreboard is misleading within the API, given anything but basic translation/literal will not be rendered. We'll need to expose the ability to write translated messages somehow else.

2020-11-24 12:23 UTC, arthurbambou commented
@Gegy Can you review again?
I changed it so it doesn’t use a Text anymore

2020-11-24 13:31 UTC, arthurbambou commented
Close in favor of #63

2020-11-24 13:31 UTC, closed without merging