Add Luckperms Fabric Api support & basic api
NucleoidMC/plasmid pull request #99
Opened 2021-01-06 23:17 UTC by hYdos

The title says all. if you need more information ping me on discord and ill put it here

2021-01-06 23:24 UTC, PotatoPresident requested changes

2021-01-06 23:24 UTC, PotatoPresident commented on src/main/java/xyz/nucleoid/plasmid/command/GameChannelCommand.java
> +                        .requires(Permissions.require("plasmid.command.game_channel"))
Change to Permissions.require("plasmid.command.game_channel", 3) which would make 3 a default in case the server isn't using a permission mamanger.

2021-01-06 23:24 UTC, PotatoPresident commented on src/main/java/xyz/nucleoid/plasmid/command/GameCommand.java
> +                        .requires(Permissions.require("plasmid.command.game.open"))
Change to Permissions.require("plasmid.command.game_channel", 2) which would make 2 a default in case the server isn't using a permission mamanger.

2021-01-06 23:24 UTC, PotatoPresident commented on src/main/java/xyz/nucleoid/plasmid/command/GameCommand.java
> +                        .requires(Permissions.require("plasmid.command.game.propose"))
Same as above

2021-01-06 23:24 UTC, PotatoPresident commented on src/main/java/xyz/nucleoid/plasmid/command/GameCommand.java
> +                        .requires(Permissions.require("plasmid.command.game.stop"))
same as above

2021-01-06 23:24 UTC, PotatoPresident commented on src/main/java/xyz/nucleoid/plasmid/command/GameCommand.java
> +                        .requires(Permissions.require("plasmid.command.game.joinall"))
same as above

2021-01-06 23:24 UTC, PotatoPresident commented on src/main/java/xyz/nucleoid/plasmid/command/MapManageCommand.java
> +            literal("map").requires(Permissions.require("plasmid.command.map"))
same again

2021-01-06 23:24 UTC, PotatoPresident commented on src/main/java/xyz/nucleoid/plasmid/command/MapMetadataCommand.java
> +            literal("map").requires(Permissions.require("plasmid.command.map"))
I probably didn't need to comment on all of these

2021-01-06 23:28 UTC, ShockMicro commented
Doesn't Leukocyte do permissions? Why is this needed?

2021-01-06 23:30 UTC, hYdos commented
> Doesn't Leukocyte do permissions? Why is this needed?

Leukocyte is a  "Region-based protection controllable by API or commands "

2021-01-07 03:56 UTC, ramidzkh requested changes

2021-01-07 03:56 UTC, ramidzkh commented on build.gradle
> +  modImplementation 'me.lucko:fabric-permissions-api:0.1-SNAPSHOT'
Since this is the API, include it with the built library

2021-01-07 03:56 UTC, ramidzkh commented on src/main/java/xyz/nucleoid/plasmid/fake/FakeBlockItem.java
> +public class FakeBlockItem extends Item implements FakeItem {
Unrelated to PR

2022-03-15 19:08 UTC, closed without merging